### ISSUE TITLE
How can I use this to completely suppress the windows welcome screen UI elements?

### ISSUE THREAD

**Issue by jazir555** [VoidVolker/Windows-logon-service#1]
Hi there, I'm trying to suppress the Windows 11 logon UI welcome screen animation. Can this be done with your tool? Inserting a full #000000 black jpg over the UI would work if it can't be fully disabled.

**Comment by VoidVolker** [comment]
Hi  @jazir555,

I don't know if logon UI can be hided - need to take a look inside of logon UI. Creating simple full screen app with topmost window with black background and starting it at logon screen will work. Here is an example of app running in UI screen of Windows 10:
![LogonApplication](https://github.com/VoidVolker/Windows-logon-service/assets/5086438/23dfd564-a8b7-43d2-a96d-3205aa40c341)
As you can see it overlaps UI controls.

With windows 11 it wasn't tested yet. Let me know if you have any issues with win 11.

**Comment by jazir555** [comment]
There's no documentation on the repo that I can find, how would I go about testing this? I have my computer configured to auto logon, so the lockscreen isn't displayed. 

My boot process looks like: Computer turns on > Windows boot logo + spinning wheel > Lockscreen automatically bypassed > [welcome screen](https://imgur.com/a/7nkuciw) > default shell

My thought process right now is to have the black jpg display as soon as the boot logo disappears, and to remove it after the welcome UI disappears and the default shell launches, which in my case is Steam Big Picture.

The end goal is have to Windows boot straight to Steam Big Picture with no UI elements appearing whatsoever(black screen) until Steam launches.

**Comment by VoidVolker** [comment]
Ok, I see. I'll rebuild app with latest dotnet and add some more features to make it more usable.

**Comment by VoidVolker** [comment]
@jazir555 hey dude! I just released updated version: with compiled binaries and configuration in file. Check releases page to get it and start using: https://github.com/VoidVolker/Windows-logon-service/releases/ (all config details in [readme](https://github.com/VoidVolker/Windows-logon-service/blob/master/README.md)). Let me know what you think and if it works fine in Windows 11.

**Comment by VoidVolker** [comment]
Also I completed research of logon screen window structure by running window scanner at logon: process `LogonUI.exe` creates that window. Getting this window handle inside app running at logon screen allows to hide logon window completely and get clear black screen. But I meet next issue: standard API calls like `EnumWindows`, `EnumThreadWindows` and `GetWindowThreadProcessId` doesn't returns LogonUI window handle, but InqSoft Window Scanner was able to catch ALL windows. Looks like it uses some other meachanizm for scanning windows tree. 

Anyway, for your case you can create an app with black fullscrenn window with topmost flag - alt+tab is working nicely at logon screen too. And run it at logon screen using logon service. When autologon complete logging in - logon app will be killed automatically.

**Comment by VoidVolker** [comment]
Founded very simple solution: `GetForegroundWindow` call when no other windows is activated. I don't tested it after windows boot, but it shall works. Also there can be a lag of starting logon service after windows boots - nothing can't be done with that.

UPD

Final solution:
```c#
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml.Linq;

namespace HideWinLogonUI
{
    internal class Program
    {
        const int sleepTimer = 25;
        const int SW_HIDE = 0;
        //const int SW_SHOW = 5;
        [DllImport("User32")]
        static extern int ShowWindow(IntPtr hwnd, int nCmdShow);
        //static void WindowShow(IntPtr hwnd) => ShowWindow(hwnd, SW_SHOW);
        static void WindowHide(IntPtr hwnd) => ShowWindow(hwnd, SW_HIDE);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool IsWindowVisible(IntPtr hWnd);

        [DllImport("user32.dll")]
        static extern uint GetWindowThreadProcessId(IntPtr hWnd, out int ProcessId);

        static void Main(string[] args)
        {
            while (true)
            {
                if (LogonUI.TryProc() is Process logonProc)
                {
                    if (IsWindowVisible(logonProc.MainWindowHandle))
                    {
                        WindowHide(logonProc.MainWindowHandle);
                        break;
                    }
                }
                Thread.Sleep(sleepTimer);
            }
        }

        class Util
        {
            public static Process? TryProc(string name, string fullPath)
            {
                Process[] processes = Process.GetProcessesByName(name);
                foreach (var proc in processes)
                {
                    if (fullPath.Equals(proc.MainModule?.FileName, StringComparison.InvariantCultureIgnoreCase))
                    {
                        return proc;
                    }
                }
                return null;
            }
        }

        static class LogonUI
        {
            const string LogonName = "LogonUI";
            const string LogonExe = LogonName + ".exe";
            static readonly string logonPath = Path.GetFullPath(@"C:\Windows\System32\" + LogonExe);

            public static Process? TryProc() => Util.TryProc(LogonName, logonPath);
        }
    }
}
```

**Comment by jazir555** [comment]
Oh man, I've been busy for the last couple days. Just saw all this. Gonna dig in tonight and I'll get back to you! Thank you for looking into this!

**Comment by jazir555** [comment]
> Founded very simple solution: `GetForegroundWindow` call when no other windows is activated. I don't tested it after windows boot, but it shall works. Also there can be a lag of starting logon service after windows boots - nothing can't be done with that.

How would I go about testing this? I'm not very good at coding, and not sure exactly where to start. I'd be happy to donate if you have time to work on it.

**Comment by VoidVolker** [comment]
@jazir555 
Hers is binaries of test app: [testapp.zip](https://github.com/VoidVolker/Windows-logon-service/files/14259727/testapp.zip) - unpack it to your disk, add full path to `TestApp.exe` to logon service config, install or restart service and lock or reboot PC to see how it works.

>  I'd be happy to donate if you have time to work on it.

You can find me in tm and we can discuss details and I can build an app for you.

**Comment by jazir555** [comment]
>You can find me in tm and we can discuss details and I can build an app for you.

Which platform is tm? Would like to discuss further

**Comment by VoidVolker** [comment]
jazir555 tm = Telegram messanger

**Comment by jazir555** [comment]
> jazir555 tm = Telegram messanger

Cool, same username? Assuming so, just sent you a message.
