### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DevX-Cipher** [VoidVolker/Windows-logon-service#2]
this would be great of launching this from a usb the user then requestion command prompt to remove forgotten password

**Comment by VoidVolker** [comment]
You can install logon service to any folder you want and on usb too. Btw, this service initially was developed to run custom application on logon screen with button to recovery password. In your case just configure service to run your password recovery app.

**Comment by DevX-Cipher** [comment]
but you can just run the cmd from the usb right

**Comment by VoidVolker** [comment]
What you mean? You can run cmd in any folder you want.
